export const DEFAULT_REGISTER_CYCLE = 5 * 1000;
export const DEFAULT_REGISTER_CHECK_CYCLE = 1000;
export const DEFAULT_CLEANUP_CYCLE = 5 * 1000;
export const DEFAULT_REFRESH_CYCLE = 2 * 1000;
export const DEFAULT_RECOVERY_CYCLE = 1000;
export const DEFAULT_LIVE_STATE_CLEANUP_CYCLE = 1000;
