apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.metadata.name }}
roleRef:
  kind: Role
  name: {{ .Values.metadata.name }}
  apiGroup: rbac.authorization.k8s.io
