apiVersion: v2
name: stmgr-postgres
description: stmgr-postgres
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: 16.6.0
    repository: https://charts.bitnami.com/bitnami
